name: Check status pods

on:
  workflow_dispatch

env:
  output: output.log
  report_fail: report_fail.log

jobs:
  check:
    name: Check status pods K3s
    runs-on: ubuntu-latest

    steps:
    - name: Connect to server with K3s
      run: |
        ls -la

